spring.application.name=micro-mentorship-backend
server.port = 8081
spring.datasource.url=jdbc:postgresql://localhost:5432/mentorship_db
spring.datasource.username=postgres
spring.datasource.password=RadhaKrishna
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akshat2019cs059abesit@gmail.com
spring.mail.password=sharmaakshat01
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.sql.init.mode = always
spring.jpa.defer-datasource-initialization = true 


